src/Entity/AccountGroup.php
<?php

namespace App\Entity;


use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 * @ORM\Table(name="account_group")
 */
class AccountGroup
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank()
     */
    private $title;

    /**
     * One Group has Many Accounts.
     * @ORM\OneToMany(targetEntity="Account", mappedBy="group")
     */
    private $accounts;

    /**
     * Many AccountGroups have One User.
     * @ORM\ManyToOne(targetEntity="User", inversedBy="account_groups")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    private $user;

    public function __construct()
    {
        $this->accounts = new ArrayCollection();
    }

    /**
     * @return int
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * @param string $title
     * @return AccountGroup
     */
    public function setTitle(string $title): AccountGroup
    {
        $this->title = $title;
        return $this;
    }

    /**
     * @return Collection | Account[]
     */
    public function getAccounts(): ?Collection
    {
        return $this->accounts;
    }

    /**
     * @param mixed $accounts
     * @return AccountGroup
     */
    public function setAccounts($accounts): AccountGroup
    {
        $this->accounts = $accounts;
        return $this;
    }

    /**
     * @param Account $account
     * @return AccountGroup
     */
    public function addAccount(Account $account): AccountGroup
    {
        if (!$this->accounts->contains($account)) {
            $this->accounts->add($account);
        }
        return $this;
    }

    /**
     * @param Account $account
     * @return AccountGroup
     */
    public function removeAccount(Account $account): AccountGroup
    {
        if ($this->accounts->contains($account)) {
            $this->accounts->removeElement($account);
        }
        return $this;
    }

    /**
     * @return User
     */
    public function getUser(): ?User
    {
        return $this->user;
    }

    /**
     * @param User $user
     * @return AccountGroup
     */
    public function setUser(User $user): AccountGroup
    {
        $this->user = $user;
        return $this;
    }

    public function getTotalAccountGroupBalance()
    {
        $balance = 0;
        /** @var Account $account */
        foreach ($this->accounts as $account) {
            $balance += $account->getBalance();
        }
        return $balance;
    }

}

templates/includes/account_group_block.html.twig
<div class="card bg-light mb-3 card_home">
    <div class="card-header p-2">
        <div class="m-0 d-flex justify-content-between">
            <h5 class="m-0">{{ group.title }}
            </h5>
            <span class="mr-auto">
                <a href="{{ path('edit_account_group',{'id':group.id}) }}"
                   class="mx-2 text-muted opacity_25 z_1000">
                    <i class="fa fa-pencil"></i>
                </a>
            </span>
            <h5 class="m-0 font-weight-bold
                {% if group.totalAccountGroupBalance > 0 %}
                text-success
                {% else %}
                text-danger
                {% endif %}
                ">{{ group.totalAccountGroupBalance }}
            </h5>
        </div>
    </div>

    <div class="card-body">
        <ul class="list-group list-group-flush">
            {% for account in group.accounts %}
                {% include 'includes/list_accounts.html.twig' with {'account': account} %}
            {% endfor %}
        </ul>
    </div>
</div>

templates/includes/create_account_block.html.twig
{% block create_account %}
    <div class="card bg-light mb-3 card_home">
        <div class="card-body">
            <div class="card-header p-2" data-toggle="collapse" href="#create_account_block"
                 role="button">
                <div class="m-0 p-0">
                    <h6 class="m-0">Create an account</h6>
                </div>
            </div>
            <div class="m-0 p-0 collapse" id="create_account_block">
                {% include 'account/create.html.twig' with {'form': form} %}
            </div>
        </div>
    </div>
{% endblock create_account %}

templates/includes/create_group_block.html.twig
{% block create_group %}
<div class="card bg-light mb-3 card_home">
    <div class="card-body">
        <div class="card-header p-2" data-toggle="collapse" href="#create_account_group_block"
             role="button">
            <h6 class="m-0">Create a group</h6>
        </div>
        <div class="m-0 p-0 collapse" id="create_account_group_block">
            {% include 'account_group/create.html.twig' with {'form': form} %}
        </div>
    </div>
</div>
{% endblock create_group %}

templates/includes/list_accounts.html.twig
<li class="listItem list-group-item d-flex justify-content-between mx-1 p-1" draggable="true">
    <a href="{{ path('account_page',{'id': account.id}) }}">{{ account.name }}
    </a>
    <span class="mr-auto">
        <a href="{{ path('edit_account',{'id':account.id}) }}"
           class="mx-2 text-muted opacity_25">
            <i class="fa fa-pencil"></i>
        </a>
    </span>
    {% if account.planning == false %}
        <span class="m-0 font-weight-bold
        {% if account.balance > 0 %}
        text-success
        {% else %}
        text-danger
        {% endif %}
        ">{{ account.balance }}
    </span>
    {% else %}
        <span class="badge badge-info">Planning</span>
    {% endif %}
</li>